name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install Near CLI
        run: cargo install near-cli-rs

      - name: Install Near
        run: cargo install cargo-near

      - name: Install near workspaces
        run: cargo add near-workspaces
        
      - name: Build project
        run: cargo build --release

      - name: Run tests
        run: cargo test
